### ISSUE TITLE
Crashing in level editor.

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#269]
_From [Cory.Pou...@gmail.com](https://code.google.com/u/105220164791991617712/) on October 25, 2013 19:37:27_

What steps will reproduce the problem? 1. place a poly wall or laodout/ goal zone onto 1 point.
2. load the level.
3. poly walls will cause walls not to draw. (but they are there.) zones will crash the game. What is the expected output? What do you see instead? crashing. or not drawing. see step 3 of problem reproduction. What version of the product are you using? On what operating system? bitfighter-019-beta-8327-b2e4bb866803-windows on a windows 7 operating system. Please provide any additional information below. source by amgine.

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=269_

**Comment by raptor** [comment]
_From [Cory.Pou...@gmail.com](https://code.google.com/u/105220164791991617712/) on October 25, 2013 19:46:03_

poly walls result in a non draw of them.

load out zones  result in crash Assert: Vector is empty in c:\hg\bitfighter\tnl\tnlvector.h line 245

goal zones result in crash Assert: unpackUpdate did not match packUpdate for object of class GoalZone. Expected 1336 bits, got 2420 bits. in c:\hg\bitfighter\tnl\ghostconnection.cpp line 536

barriers result in no problem.

polywalls results in the objects not drawing. but being there.

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on October 29, 2013 20:59:43_

Just to be clear: all of these tests are done by taking all vertices of an object and putting them onto one point.

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on October 30, 2013 20:35:09_

**Labels:** 019

**Comment by raptor** [comment]
_From [bkcon...@gmail.com](https://code.google.com/u/112584966209893525339/) on October 30, 2013 23:53:23_

GoalZone error:
Assert: unpackUpdate did not match packUpdate for object of class GoalZone. Expected 377 bits, got 373 bits. in /home/kaen/code/bitfighter-clean/tnl/ghostConnection.cpp line 536

Program received signal SIGTRAP, Trace/breakpoint trap.
TNL::GhostConnection::readPacket (this=0x1522450, bstream=0x7fffffffd310)
    at /home/kaen/code/bitfighter-clean/tnl/ghostConnection.cpp:539
539	         if(mErrorBuffer[0])
(gdb) bt
\#0  TNL::GhostConnection::readPacket (this=0x1522450, bstream=0x7fffffffd310)
    at /home/kaen/code/bitfighter-clean/tnl/ghostConnection.cpp:539
\#1  0x000000000079e3ef in Zap::ControlObjectConnection::readPacket (
    this=0x1522450, bstream=0x7fffffffd310)
    at /home/kaen/code/bitfighter-clean/zap/controlObjectConnection.cpp:252
\#2  0x0000000000b6928c in TNL::NetConnection::readRawPacket (this=0x1522450, 
    bstream=0x7fffffffd310)
    at /home/kaen/code/bitfighter-clean/tnl/netConnection.cpp:258
\#3  0x0000000000b6a927 in TNL::NetConnection::sendPacket (this=0x14e3c70, 
    stream=0x7fffffffd310)
    at /home/kaen/code/bitfighter-clean/tnl/netConnection.cpp:742
\#4  0x0000000000b6a675 in TNL::NetConnection::checkPacketSend (this=0x14e3c70, 
    force=false, curTime=28249)
    at /home/kaen/code/bitfighter-clean/tnl/netConnection.cpp:704
\#5  0x0000000000b6d764 in TNL::NetInterface::processConnections (
    this=0x1490810)
    at /home/kaen/code/bitfighter-clean/tnl/netInterface.cpp:356
\#6  0x00000000008dffc3 in Zap::ServerGame::idle (this=0x148d610, timeDelta=335)
    at /home/kaen/code/bitfighter-clean/zap/ServerGame.cpp:1116
\#7  0x0000000000b201e2 in Zap::gameIdle (timeDelta=335)
    at /home/kaen/code/bitfighter-clean/zap/main.cpp:302
\#8  0x0000000000b204dc in Zap::idle ()
    at /home/kaen/code/bitfighter-clean/zap/main.cpp:379

LoadoutZone Error:
Assert: Vector is empty in /home/kaen/code/bitfighter-clean/tnl/tnlVector.h line 245

Program received signal SIGTRAP, Trace/breakpoint trap.
TNL::Vector<Zap::Point>::first (this=0x14daa40)
    at /home/kaen/code/bitfighter-clean/tnl/tnlVector.h:246
246	   return *this->innerVector.begin();
(gdb) bt
\#0  TNL::Vector<Zap::Point>::first (this=0x14daa40)
    at /home/kaen/code/bitfighter-clean/tnl/tnlVector.h:246
\#1  0x00000000007510d9 in Zap::BfObject::collisionPolyPointIntersect (
    this=0x14da8b0, center=..., radius=24)
    at /home/kaen/code/bitfighter-clean/zap/BfObject.cpp:1150
\#2  0x00000000008e987b in Zap::Ship::isOnObject (this=0x11cbd60, 
    object=0x14da8b0) at /home/kaen/code/bitfighter-clean/zap/ship.cpp:430
\#3  0x000000000080d772 in Zap::GameType::spawnShip (this=0x1518af0, clientInfo=
    0x1501010) at /home/kaen/code/bitfighter-clean/zap/gameType.cpp:1371
\#4  0x000000000080efc6 in Zap::GameType::serverAddClient (this=0x1518af0, 
    clientInfo=0x1501010)
    at /home/kaen/code/bitfighter-clean/zap/gameType.cpp:1798
\#5  0x00000000008dfb5a in Zap::ServerGame::addClient (this=0x14e0aa0, 
    clientInfo=0x1501010)
    at /home/kaen/code/bitfighter-clean/zap/ServerGame.cpp:998
\#6  0x00000000007db367 in Zap::GameConnection::onConnectionEstablished_server (
    this=0x14d2340)
    at /home/kaen/code/bitfighter-clean/zap/gameConnection.cpp:1891
\#7  0x00000000007db05e in Zap::GameConnection::onConnectionEstablished (
    this=0x14d2340)
    at /home/kaen/code/bitfighter-clean/zap/gameConnection.cpp:1841
\#8  0x0000000000b6b220 in TNL::NetConnection::connectLocal (this=0x14f4ce0, 
    connectionInterface=0x12055a0, serverInterface=0x14a9210)
---Type \<return> to continue, or q \<return> to quit---
    at /home/kaen/code/bitfighter-clean/tnl/netConnection.cpp:946
\#9  0x00000000009f7701 in Zap::ClientGame::joinLocalGame (this=0x11f7370, 
    remoteInterface=0x14a9210)
    at /home/kaen/code/bitfighter-clean/zap/ClientGame.cpp:131
\#10 0x0000000000b2005e in Zap::hostGame (serverGame=0x14e0aa0)
    at /home/kaen/code/bitfighter-clean/zap/main.cpp:228
\#11 0x0000000000b203a2 in Zap::idle ()
    at /home/kaen/code/bitfighter-clean/zap/main.cpp:353
\#12 0x0000000000b20611 in Zap::dedicatedServerLoop ()
    at /home/kaen/code/bitfighter-clean/zap/main.cpp:427
\#13 0x0000000000b22f49 in main (argc=5, argv=0x7fffffffdfc8)
    at /home/kaen/code/bitfighter-clean/zap/main.cpp:1217

**Status:** Accepted  
  **Labels:** -Priority-Medium Priority-High

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on November 02, 2013 17:58:35_

Degenerate zones are no longer loaded from level files... this fixes all observed crashing scenarios.

**Status:** Fixed
