### ISSUE TITLE
Mysterious "empty vertex problem"

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#277]
_From [bkcon...@gmail.com](https://code.google.com/u/112584966209893525339/) on October 31, 2013 00:52:14_

Wasn't able to make a reproduction case, but I caught this crash in gdb while hovering over a certain polywall

Assert: Empty vertex problem in /home/kaen/code/bitfighter-clean/zap/UIEditor.cpp line 2651

Program received signal SIGTRAP, Trace/breakpoint trap.
Zap::EditorUserInterface::checkForEdgeHit (this=0x12b3530, point=..., object=
    0x145d160) at /home/kaen/code/bitfighter-clean/zap/UIEditor.cpp:2653
2653	   bool loop = (object->getGeomType() == geomPolygon);
(gdb)  bt
\#0  Zap::EditorUserInterface::checkForEdgeHit (this=0x12b3530, point=..., 
    object=0x145d160) at /home/kaen/code/bitfighter-clean/zap/UIEditor.cpp:2653
\#1  0x0000000000aad012 in Zap::EditorUserInterface::findHitItemAndEdge (
    this=0x12b3530) at /home/kaen/code/bitfighter-clean/zap/UIEditor.cpp:2599
\#2  0x0000000000aadce6 in Zap::EditorUserInterface::onMouseMoved (
    this=0x12b3530) at /home/kaen/code/bitfighter-clean/zap/UIEditor.cpp:2816
\#3  0x0000000000a05bb0 in Zap::Event::onMouseMoved (currentUI=0x12b3530, 
    x=720, y=443, mode=Zap::DISPLAY_MODE_WINDOWED)
    at /home/kaen/code/bitfighter-clean/zap/Event.cpp:393
\#4  0x0000000000a05254 in Zap::Event::onEvent (game=0x11f7370, 
    event=0x7fffffffdd20) at /home/kaen/code/bitfighter-clean/zap/Event.cpp:216
\#5  0x0000000000b20576 in Zap::idle ()
    at /home/kaen/code/bitfighter-clean/zap/main.cpp:405
\#6  0x0000000000b20611 in Zap::dedicatedServerLoop ()
    at /home/kaen/code/bitfighter-clean/zap/main.cpp:427
\#7  0x0000000000b22f49 in main (argc=5, argv=0x7fffffffdfc8)
    at /home/kaen/code/bitfighter-clean/zap/main.cpp:1217

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=277_

**Comment by raptor** [comment]
_From [bkcon...@gmail.com](https://code.google.com/u/112584966209893525339/) on October 30, 2013 23:53:50_

**Labels:** 019

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on November 02, 2013 16:20:54_

No idea how to track this down, but 
1) added some debugging suggestions to the assert in case it happens again; and
2) added a check for the condition with a return to prevent production crashes

Going to close this because I don't know what else to do at this point.

**Status:** Done
