### ISSUE TITLE
TNL-related assert triggered when testing from editor

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#291]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on November 09, 2013 00:17:46_

What steps will reproduce the problem? 1.  Open level in editor
2.  Test Level
3.  Assert!

stack trace:
Assert: Invalid checksum. in bitfighter/tnl/eventConnection.cpp line 426

Program received signal SIGTRAP, Trace/breakpoint trap.
TNL::EventConnection::readPacket (this=0x1a33730, bstream=0x7fffffffcfd0)
    at bitfighter/tnl/eventConnection.cpp:429
429        S32 prevSeq = -2;
(gdb) bt
\#0  TNL::EventConnection::readPacket (this=0x1a33730, bstream=0x7fffffffcfd0)
    at bitfighter/tnl/eventConnection.cpp:429
\#1  0x0000000000bafda6 in TNL::GhostConnection::readPacket (this=0x1a33730, bstream=0x7fffffffcfd0)
    at bitfighter/tnl/ghostConnection.cpp:446
\#2  0x00000000007eb57a in Zap::ControlObjectConnection::readPacket (this=0x1a33730, bstream=0x7fffffffcfd0)
    at bitfighter/zap/controlObjectConnection.cpp:232
\#3  0x0000000000bb96fe in TNL::NetConnection::readRawPacket (this=0x1a33730, bstream=0x7fffffffcfd0)
    at bitfighter/tnl/netConnection.cpp:258
\#4  0x0000000000bbad73 in TNL::NetConnection::sendPacket (this=0x1b921a0, stream=0x7fffffffcfd0)
    at bitfighter/tnl/netConnection.cpp:742
\#5  0x0000000000bbaac1 in TNL::NetConnection::checkPacketSend (this=0x1b921a0, force=false, curTime=36445)
    at bitfighter/tnl/netConnection.cpp:704
\#6  0x0000000000bbdb0c in TNL::NetInterface::processConnections (this=0x14e9350)
    at bitfighter/tnl/netInterface.cpp:356
\#7  0x000000000092fcf7 in Zap::ServerGame::idle (this=0x219f6b0, timeDelta=78)
    at bitfighter/zap/ServerGame.cpp:1095
\#8  0x0000000000b70d3f in Zap::gameIdle (timeDelta=78) at bitfighter/zap/main.cpp:280
\#9  0x0000000000b71045 in Zap::idle () at bitfighter/zap/main.cpp:357
\#10 0x0000000000b71181 in Zap::dedicatedServerLoop () at bitfighter/zap/main.cpp:405
\#11 0x0000000000b73b38 in main (argc=1, argv=0x7fffffffdd08) at bitfighter/zap/main.cpp:1202

Note this is not due to addition of copy constructor in NetObject in r404290c12f35 (already tested)

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=291_

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on November 09, 2013 08:09:08_

Fixed by a reversion in rbe309746a53b What is the mFireTimer??

**Status:** Fixed  
  **Owner:** buckyballreaction
