### ISSUE TITLE
Assert after hitting ESC while connecting to a server

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#331]
_From [bkcon...@gmail.com](https://code.google.com/u/112584966209893525339/) on December 05, 2013 11:34:16_

What steps will reproduce the problem? 1. Join a server
2. Hit ESC while connecting
3. Choose Join Server from the menu What is the expected output? What do you see instead? I expect it to work fine, but I get an assert:

Assert: Pushing duplicate UI onto mPrevUIs stack.  Intentional? in /home/kaen/code/bitfighter-hg/zap/UIManager.cpp line 192

Program received signal SIGTRAP, Trace/breakpoint trap.
Zap::UIManager::saveUI (this=0x8db2ef0, ui=0x90b1248)
    at /home/kaen/code/bitfighter-hg/zap/UIManager.cpp:194
194	   if(ui)
(gdb) bt
\#0  Zap::UIManager::saveUI (this=0x8db2ef0, ui=0x90b1248)
    at /home/kaen/code/bitfighter-hg/zap/UIManager.cpp:194
\#1  0x0869afe0 in Zap::UIManager::activate (this=0x8db2ef0, ui=0x90b1c98, 
    save=true) at /home/kaen/code/bitfighter-hg/zap/UIManager.cpp:173
\#2  0x086b8a7b in Zap::UIManager::activate<Zap::QueryServersUserInterface> (
    this=0x8db2ef0, save=true)
    at /home/kaen/code/bitfighter-hg/zap/UIManager.h:113
\#3  0x086aded3 in Zap::joinSelectedCallback (game=0x8daf800, unused=4294967295)
    at /home/kaen/code/bitfighter-hg/zap/UIMenus.cpp:890
\#4  0x0869f036 in Zap::MenuItem::handleKey (this=0x90b13f0, 
    inputCode=Zap::KEY_ENTER)
    at /home/kaen/code/bitfighter-hg/zap/UIMenuItems.cpp:192
\#5  0x086ad93c in Zap::MenuUserInterface::processKeys (this=0x90b1248, 
    inputCode=Zap::KEY_ENTER) at /home/kaen/code/bitfighter-hg/zap/UIMenus.cpp:681
\#6  0x086ad61a in Zap::MenuUserInterface::onKeyDown (this=0x90b1248, 
    inputCode=Zap::KEY_ENTER) at /home/kaen/code/bitfighter-hg/zap/UIMenus.cpp:604
\#7  0x086adea3 in Zap::MenuUserInterfaceWithIntroductoryAnimation::onKeyDown (
    this=0x90b1248, inputCode=Zap::KEY_ENTER)
    at /home/kaen/code/bitfighter-hg/zap/UIMenus.cpp:870
\#8  0x085d3ff4 in Zap::Event::inputCodeDown (currentUI=0x90b1248, 
    inputCode=Zap::KEY_ENTER) at /home/kaen/code/bitfighter-hg/zap/Event.cpp:177
\#9  0x085d4962 in Zap::Event::onKeyDown (game=0x8daf800, event=0xbffff1f4)
    at /home/kaen/code/bitfighter-hg/zap/Event.cpp:369
\#10 0x085d405e in Zap::Event::onEvent (game=0x8daf800, event=0xbffff1f4)
    at /home/kaen/code/bitfighter-hg/zap/Event.cpp:191
\#11 0x086cee12 in Zap::idle () at /home/kaen/code/bitfighter-hg/zap/main.cpp:384
\#12 0x086ceeac in Zap::dedicatedServerLoop ()
    at /home/kaen/code/bitfighter-hg/zap/main.cpp:406
\#13 0x086d1793 in main (argc=1, argv=0xbffff3d4)
    at /home/kaen/code/bitfighter-hg/zap/main.cpp:1219

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=331_

**Comment by raptor** [comment]
_From [sam8641@gmail.com](https://code.google.com/u/sam8641@gmail.com/) on December 20, 2013 09:46:42_

Fixed on Revision 5c695069f697

**Status:** Fixed
