### ISSUE TITLE
Bitfighter sometimes crashes on start-up with a USB mouse on OS X

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#99]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on May 15, 2011 20:06:59_

Sometimes, with a USB mouse attached, Bitfighter will crash on start-up with the following error:

3125 Bus error

The following is the error and a stack trace when running through gdb:

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_PROTECTION_FAILURE at address: 0x00000005
0x92554845 in CFGetTypeID ()

\#0  0x92554845 in CFGetTypeID ()
\#1  0x000b100d in Zap::InitJoystick ()
\#2  0x000a9237 in main ()
\#3  0x00013d6a in _start ()
\#4  0x00013c91 in start ()

There is apparently some conflict with the joystick code in osxInput.cpp - most likely accessing a NULL pointer (but not sure.)

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=99_

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on May 15, 2011 19:07:07_

**Status:** New

**Comment by raptor** [comment]
_From [buckyballreaction](https://code.google.com/u/buckyballreaction/) on August 15, 2011 22:52:37_

This may not be an issue anymore with the move to SDL.  All joystick code is the same now for all platforms.  

Marking WontFix.

Open a different issue if similar problems still arise - they would be with completely unrelated code.

**Status:** WontFix  
  **Owner:** buckyballreaction
